### ISSUE TITLE
Reconcile prototype with Storybook 

### ISSUE THREAD

**Issue by edward-malouf** [codeforboston/jobhopper#161] opened 2020-10-26 01:05 UTC
Attached
[Storybook review 2.txt](https://github.com/codeforboston/jobhopper/files/5436295/Storybook.review.2.txt)
 is the review of the Storybook components URL with the Figma prototype

**Comment by jedpittman** [comment] 2020-10-27 23:44
closing this as duplicate of #146

**Closed by jedpittman** 2020-10-27 23:44 UTC
