### ISSUE TITLE
Make sure the OccupationTransitions API is working correctly

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#159] opened 2020-10-25 19:08 UTC
The OccupationTransitions API, accessible after running `python manage.py runserver` at http://127.0.0.1:8000/api/v1/jobs/transitions/, is showing a count of 0 occupation transitions. It should show all transitions in the transitions table.  

```
HTTP 200 OK
Allow: GET, POST, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "count": 0,
    "next": null,
    "previous": null,
    "results": []
}
```

Suggested fix: 
* Review migration 0009 in `jobs/migrations` to make sure the data is loaded correctly 
* Make sure the table is correctly wired to the URL by checking `urls.py`, `api.py`, and `serializers.py`

**Comment by jedpittman** [comment] 2020-10-25 19:29
@l-cheung, I am not sure what the cause may be here. On my develop branch, I follow these steps:
1. Check all migrations are applied
python migrate.py showmigrations
2. Check the tests run
python migrate.py test
3. Start the server
python migrate.py runserver
4. Go to the swagger endpoint (first step)
http://127.0.0.1:8000/api/v1/docs

**This step takes FOREVER!! And I want to talk more to J (spelling?) about it. **

Once I get that done, I can go down to transitions and it works (see below)


![image](https://user-images.githubusercontent.com/18365706/97116855-75cb4400-16d6-11eb-8c33-d347d84d4006.png)

If those steps don't work for you please let me know. Maybe my machine is messed up again :(

**Comment by l-cheung** [comment] 2020-10-26 10:21
I'm still getting no data in the jobs_occupationtransitions table :( 

![image](https://user-images.githubusercontent.com/35081231/97159975-0d21ad00-1752-11eb-8feb-9fc0ae916de4.png)

It's possible something's messed up on my machine, too.  Steps I took:

* Checkout upstream develop branch
```
git fetch upstream
git checkout -b dev_check upstream/develop
```

* Check tests & re-run all migrations and check that they've all been run
```
python manage.py test
python manage.py migrate jobs zero
python manage.py migrate
python manage.py showmigrations
```

```
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
 [X] 0010_alter_group_name_max_length
 [X] 0011_update_proxy_permissions
 [X] 0012_alter_user_first_name_max_length
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
jobs
 [X] 0001_initial
 [X] 0002_occupationtransitions
 [X] 0003_auto_20200909_1254
 [X] 0004_auto_20200909_1255
 [X] 0005_auto_20200914_1220
 [X] 0006_blsoesfakes
 [X] 0007_stateabbpairs
 [X] 0008_auto_20201006_AddStateData
 [X] 0009_auto_20201013_2033
 [X] 0010_blsoes
 [X] 0011_auto_20201024_2201
sessions
 [X] 0001_initial
```

* Run `python manage.py runserver` and go to http://127.0.0.1:8000/api/v1/docs
* Execute a transitions GET request

Does it still work for you if you start with a clean `jobs_occupationtransitions` table?

**Comment by jedpittman** [comment] 2020-11-01 22:09
closing with #168

**Closed by jedpittman** 2020-11-01 22:09 UTC
