### ISSUE TITLE
Update occupation transitions dataset with latest version

### ISSUE THREAD

**Issue by l-cheung** [codeforboston/jobhopper#256] opened 2021-01-09 14:55 UTC
Anna provided an updated transitions dataset in January 2021 that needs to be incorporated into the backend. 

Request:
"(1) The variable we want to use is called "transition_share"
(2) The high level occupation group to color code on in the tree maps is in the file "soc_hierarchy". The one we want to group on is "majorgroup" (which gives the soc code) and "majorname" (the corresponding name of the occupation group). The variable we have in the other file corresponds to "detailedoccupation" (soc code) and "detailedname". Feel free to ignore the other columns ("broad" and "minor")."

where transition_share corresponds to pi in the original csv file `occupation_transitions_public_data_set.csv` in `api/data`

**Comment by l-cheung** [comment] 2021-01-09 17:04
See https://github.com/codeforboston/jobhopper/pull/257 

## Changelog
- Update occupation_transitions_data_set.csv with the latest version from Anna
- Replace the unused soc_structure_2018.csv file with soc_hierarchy.xlsx from Anna
- Edit load process for occupation_transitions dataset to account for new transitions_share column, which still represents the conditional probability pi
- Keep the API response similar to before, with pi representing the transitions share proportion
- Remove the unused "occleaveshare", "total_soc" fields from the transitions-extended response
- Remove old readme

**Comment by jedpittman** [comment] 2021-01-13 00:31
Closing this per Lillian. Duplicate of #257

**Closed by jedpittman** 2021-01-13 00:31 UTC
